version: '3.8'

services:
  web:
    build: .
    container_name: go-http-server
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: go run main.go 