name: Publish Docker

on:
  push:
    branches: ["master"]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: petrusariaa/go-http-server
          flavor:
            prefix: latest

      - name: Build Docker Image
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo $MONGODB_URI
          docker compose up -d
