name: Publish Docker

on:
  push:
    branches: ["master"]

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo env.MONGODB_URI
          docker compose up -d
